### ISSUE TITLE
Tutorial doesn't work 

### ISSUE THREAD

**Issue by EvadS** [Bonitasoft-Community/getting-started-tutorial#7]
this tutorial doesn't work on windows 8 

When I try to submit  a new travel request i got the exception : 
Exception in thread "main" org.h2.jdbc.JdbcSQLException: ���������� ���������: "java.net.SocketTimeoutException: connect timed out: 192.168.0.103:57656"
Connection is broken: "java.net.SocketTimeoutException: connect timed out: 192.168.0.103:57656" [90067-175]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:332)
	at org.h2.message.DbException.get(DbException.java:161)
	at org.h2.engine.SessionRemote.connectServer(SessionRemote.java:417)
	at org.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:335)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:105)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:90)
	at org.h2.Driver.connect(Driver.java:73)
	at java.sql.DriverManager.getConnection(DriverManager.java:664)
	at java.sql.DriverManager.getConnection(DriverManager.java:208)
	at org.h2.util.JdbcUtils.getConnection(JdbcUtils.java:135)
	at org.h2.util.JdbcUtils.getConnection(JdbcUtils.java:118)
	at org.h2.tools.Console.runTool(Console.java:223)
	at org.h2.tools.Console.main(Console.java:100)
Caused by: java.net.SocketTimeoutException: connect timed out
	at java.net.DualStackPlainSocketImpl.waitForConnect(Native Method)
	at java.net.DualStackPlainSocketImpl.socketConnect(DualStackPlainSocketImpl.java:85)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:172)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at org.h2.util.NetUtils.createSocket(NetUtils.java:119)
	at org.h2.util.NetUtils.createSocket(NetUtils.java:100)
	at org.h2.engine.SessionRemote.initTransfer(SessionRemote.java:100)
	at org.h2.engine.SessionRemote.connectServer(SessionRemote.java:413)
	... 10 more

**Comment by amottier** [comment]
Can you try to:

- go in the Studio settings
- click on "Database"
- select the 4 check boxes
- restart the Studio

Try to submit again the start form.

Thanks.

**Comment by amottier** [comment]
Feel free to open a new issue if you still have errors related to the database.
